services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    image: aicodebasse-backend-image:latest
    container_name: aicodebasse-backend-container
    ports:
      - "6302:6302"
      - "8491:8491"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Tokyo
    restart: always
    tty: true
    shm_size: '22.4gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: aicodebasse-frontend-image:latest
    container_name: aicodebasse-frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
      - ./frontend/.env.local    # .env と同じ名前の環境変数がある場合は .env.local の値で上書きされます。
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - backend
    restart: always
    tty: true
    shm_size: '6.4gb'
    secrets:
      - github_token

  stripe-listener:
    image: stripe/stripe-cli
    container_name: aicodebasse-stripe-listener-container
    command: ["listen", "--forward-to", "http://frontend:3000/api/webhooks"]
    env_file:
      - ./frontend/.env
    depends_on:
      - frontend
    volumes:
      - ~/.config/stripe:/root/.config/stripe
    environment:
      - TZ=Asia/Tokyo
    restart: always
    tty: true
    shm_size: '3.2gb'

secrets:
  github_token:
    file: ./github_token.txt