services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  stripe-listener:
    image: stripe/stripe-cli
    container_name: stripe-listener
    command: ["listen", "--forward-to", "http://frontend:3000/api/webhooks"]
    env_file:
      - ./frontend/.env
    depends_on:
      - frontend
    volumes:
      - ~/.config/stripe:/root/.config/stripe:ro   # ボリュームのマウント: ホストの ~/.config/stripe をコンテナにマウントし、認証情報を共有します。